yarnPath: .yarn/releases/yarn-3.2.0.cjs
packageExtensions:
  '@nestjs/graphql@*':
    peerDependencies:
      class-validator: '*'
      class-transformer: '^0.4'
  'apollo-server-express@*':
    dependencies:
      'express': '*'
